spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: testuser
    password: test123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
